export { buildReportModel } from './model'
export type { DoctorReportModel, ReportInput, ScoreSummary } from './model'
export { loadReportSources } from './load'
export type { ReportSources } from './load'
export { addDays, localDate } from './dates'
export { quantile } from './math'
export { METRIC_DEFS, periodStart } from './metrics'
export type { MetricKey, MetricSummary } from './metrics'
export { WEEKLY_KEYS } from './weekly'
export { toMarkdown, baselineCell, scoreTrendText, labStatusCell } from './markdown'
export {
  parseRefRange, LAB_STATUS_TEXT, LAB_FLAG_SUFFIX, LAB_UNIT_CAVEAT, LAB_DATE_CAVEAT,
} from './labs'
export type { LabStatus, LabLine, LabSeries, LabsSection } from './labs'
export { BAND_TEXT, POSITION_TEXT, bandOf, baselineOf, reliabilityOf, supportsClaims } from './reliability'
export type { Band, Baseline, Reliability } from './reliability'
